#Name vom Skript
name: Build & Test project with maven
# Bei jedem push soll das skript ausgeführt werden
on: push
# Was soll eig passieren?
jobs:
  build:
  # auf unbuntu ausführen
    runs-on: ubuntu-latest
# Folgendes
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "temurin"
      - name: Compile, test & package our project with Maven
        run: mvn --batch-mode package --file pom.xml
